name: Gold Bot
on:
  schedule:
    - cron: '0,30 5-20 * * 1-5'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python main.py
        timeout-minutes: 3
      - name: Save data
        run: |
          git config user.email "goldbot@auto.com"
          git config user.name "Gold Bot"
          git add data.json || true
          git diff --staged --quiet || git commit -m "update bot data"
          git push || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
